# Generated by Django 4.1.1 on 2022-11-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_customer_order_food_image_restaurant_reviews_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Product',
        ),
    ]
