# Generated by Django 4.1.1 on 2022-11-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_food_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
